#ifndef COMMON_DEFINE_H_INCLUDED
#define COMMON_DEFINE_H_INCLUDED

//#ifdef __cplusplus
//extern "C" {
//#endif

/*****************************************************************
 * Extern
 ****************************************************************/
extern uint32_t viperui_ListStdColor[];

/*****************************************************************
 * Enum
 ****************************************************************/
typedef enum
{  // Tenere allineati gli enum con la struttura viperui_StrutturaDati
   VIPERUI_DATA_MIGMAN_DTENSIONE,
   VIPERUI_DATA_MIGMAN_DVELFILO,
   VIPERUI_DATA_MIGMAN_INDUTTANZA,

   VIPERUI_DATA_MIGMANHOTSTART_DVELFILO,
   VIPERUI_DATA_MIGMANHOTSTART_DTENSIONE,
   VIPERUI_DATA_MIGMANHOTSTART_DSECDURATA,
   VIPERUI_DATA_MIGMANHOTSTART_DSECSLOPE,
   VIPERUI_DATA_MIGMANCRATERFILLER_DVELFILO,
   VIPERUI_DATA_MIGMANCRATERFILLER_DTENSIONE,
   VIPERUI_DATA_MIGMANCRATERFILLER_DSECSLOPE,
   VIPERUI_DATA_MIGMANCRATERFILLER_DSECDURATA,

   VIPERUI_DATA_MIGSYN_UISXVIS,
   VIPERUI_DATA_MIGSYN_UIDXVIS,
   VIPERUI_DATA_MIGSYN_DVELFILO,
   VIPERUI_DATA_MIGSYN_DTENSBILANCIAMENTO,
   VIPERUI_DATA_MIGSYN_INDUTTANZABILANCIAMENTO,

   VIPERUI_DATA_MIGSYNHOTSTART_PERCSPEED,
   VIPERUI_DATA_MIGSYNHOTSTART_DBALANCEV,
   VIPERUI_DATA_MIGSYNHOTSTART_DSECDURATA,
   VIPERUI_DATA_MIGSYNHOTSTART_DSECSLOPE,
   VIPERUI_DATA_MIGSYNCRATERFILLER_PERCSPEED,
   VIPERUI_DATA_MIGSYNCRATERFILLER_DBALANCEV,
   VIPERUI_DATA_MIGSYNCRATERFILLER_DSECSLOPE,
   VIPERUI_DATA_MIGSYNCRATERFILLER_DSECDURATA,

   VIPERUI_DATA_MIGSYNACTUALSYNCALC_CORRENTE,
   VIPERUI_DATA_MIGSYNACTUALSYNCALC_DSPESSORE,
   VIPERUI_DATA_MIGSYNACTUALSYNCALC_DTENSIONE,

   VIPERUI_DATA_MIG_CURVAATTUALE,
   VIPERUI_DATA_MIG_TEMPI,
   VIPERUI_DATA_MIG_BBT,
   VIPERUI_DATA_MIG_CSWIRESLOPE,
   VIPERUI_DATA_MIG_DSPOSTGAS,
   VIPERUI_DATA_MIG_DSPREGAS,
   VIPERUI_DATA_MIG_DSSPOT,

   VIPERUI_DATA_MMA_CORRENTE,
   VIPERUI_DATA_MMA_HOTSTART,
   VIPERUI_DATA_MMA_ARCFORCE,

   VIPERUI_DATA_TIG_CORRENTE,
   VIPERUI_DATA_TIG_DTENSCUTOFF,

   VIPERUI_DATA_BASE_PROCESSO,
   VIPERUI_DATA_BASE_PTOOPERATORE,
   VIPERUI_DATA_BASE_TIPOMIG,
   VIPERUI_DATA_BASE_TIPOFILO,
   VIPERUI_DATA_BASE_TIPOGAS,
   VIPERUI_DATA_BASE_DIAMETROFILO,

   VIPERUI_DATA_BASICSETUP_GRUPPOH2OEN,

   VIPERUI_DATA_TARATURAESSEN_KIO,
   VIPERUI_DATA_TARATURAESSEN_K0IO,
   VIPERUI_DATA_TARATURAESSEN_KVO,
   VIPERUI_DATA_TARATURAESSEN_K0VO,
   VIPERUI_DATA_TARATURAESSEN_KISET,
   VIPERUI_DATA_TARATURAESSEN_K0ISET,
   VIPERUI_DATA_TARATURAESSEN_FASCIOCAVIRESISTENZA,
   VIPERUI_DATA_TARATURAESSEN_FASCIOCAVIINDUTTANZA,

   VIPERUI_DATA_MIGSYN_MAX
}viperui_Data_e;


typedef enum
{
   VIPERUI_STDCOLOR_AZIENDALE,
   VIPERUI_STDCOLOR_NERO,
   VIPERUI_STDCOLOR_GRIGIOSCURO,
   VIPERUI_STDCOLOR_GRIGIOMEDIO,
   VIPERUI_STDCOLOR_GRIGIOCHIARO,
   VIPERUI_STDCOLOR_BIANCO,

   VIPERUI_STDCOLOR_MAX
}viperui_ObjColor_e;


typedef enum
{
   VIPERUI_ATUALESELEZIONEPROCESSO_TIPOPROCESSO,

   VIPERUI_ATUALESELEZIONEPROCESSO_MMA,

   VIPERUI_ATUALESELEZIONEPROCESSO_TIG,

   VIPERUI_ATUALESELEZIONEPROCESSO_MIG_TIPOMIG,
   VIPERUI_ATUALESELEZIONEPROCESSO_MIG_TIPOFILO,
   VIPERUI_ATUALESELEZIONEPROCESSO_MIG_DIAMETROFILO,
   VIPERUI_ATUALESELEZIONEPROCESSO_MIG_TIPOGAS,

   VIPERUI_ATUALESELEZIONEPROCESSO_MAX
}viperui_AttualeSelezioneProcesso_e;



//#ifdef __cplusplus
//}
//#endif

#endif //COMMON_DEFINE_H_INCLUDED
