
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: unsaved
* name: Font
* family: Prompt
* size: 14
* style: Regular
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/
#include "Font.h"
/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>



#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x20[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x20 = { image_data_Font_0x20,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x21[21] = {
    // ███
    // ███
    // ███
    // ███
    // ███
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // ███
    // ███
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x21 = { image_data_Font_0x21,
    3, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x22[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █∙█∙█
    // █∙█∙█
    // █∙█∙█
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xa8, 
    0xa8, 
    0xa8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x22 = { image_data_Font_0x22,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x23[42] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙███∙∙█
    // ████∙███∙██
    // ███∙∙███∙██
    // █∙∙∙∙∙∙∙∙∙█
    // ███∙███∙███
    // ██∙∙███∙███
    // █∙∙∙∙∙∙∙∙██
    // ██∙███∙████
    // ██∙███∙████
    // █∙∙███∙████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0x20, 
    0xf7, 0x60, 
    0xe7, 0x60, 
    0x80, 0x20, 
    0xee, 0xe0, 
    0xce, 0xe0, 
    0x80, 0x60, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0x9d, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x23 = { image_data_Font_0x23,
    11, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x24[21] = {
    // ████████
    // ████████
    // ████████
    // ███∙∙███
    // ███∙∙███
    // ██∙∙∙∙∙█
    // █∙∙∙∙█∙█
    // █∙█∙∙███
    // █∙∙∙∙███
    // ██∙∙∙███
    // ███∙∙∙██
    // ███∙∙∙∙█
    // ███∙∙█∙█
    // █∙█∙∙∙∙█
    // █∙∙∙∙∙██
    // ███∙∙███
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xe7, 
    0xe7, 
    0xc1, 
    0x85, 
    0xa7, 
    0x87, 
    0xc7, 
    0xe3, 
    0xe1, 
    0xe5, 
    0xa1, 
    0x83, 
    0xe7, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x24 = { image_data_Font_0x24,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x25[42] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ██∙∙∙███∙∙██
    // █∙██∙∙█∙∙███
    // █∙███∙█∙████
    // █∙██∙∙∙∙████
    // ██∙∙∙█∙█████
    // █████∙∙█∙∙∙█
    // █████∙█∙██∙∙
    // ████∙∙█∙███∙
    // ████∙██∙██∙∙
    // ███∙████∙∙∙█
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xc7, 0x30, 
    0xb2, 0x70, 
    0xba, 0xf0, 
    0xb0, 0xf0, 
    0xc5, 0xf0, 
    0xf9, 0x10, 
    0xfa, 0xc0, 
    0xf2, 0xe0, 
    0xf6, 0xc0, 
    0xef, 0x10, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x25 = { image_data_Font_0x25,
    12, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x26[42] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙██∙∙████
    // █∙∙██∙∙████
    // ██∙██∙█████
    // ███∙∙██████
    // ██∙∙∙∙██∙██
    // █∙███∙∙█∙██
    // █∙████∙∙∙██
    // █∙∙███∙∙∙██
    // ██∙∙∙∙∙█∙∙█
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xd9, 0xe0, 
    0x99, 0xe0, 
    0xdb, 0xe0, 
    0xe7, 0xe0, 
    0xc3, 0x60, 
    0xb9, 0x60, 
    0xbc, 0x60, 
    0x9c, 0x60, 
    0xc1, 0x20, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x26 = { image_data_Font_0x26,
    11, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x27[21] = {
    // ██
    // ██
    // ██
    // ██
    // ██
    // █∙
    // █∙
    // █∙
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    // ██
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0x80, 
    0x80, 
    0x80, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0
};
static const tImage Font_0x27 = { image_data_Font_0x27,
    2, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x28[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // ██∙∙█
    // ██∙██
    // █∙∙██
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙∙██
    // █∙∙██
    // ██∙∙█
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xc8, 
    0xd8, 
    0x98, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0x98, 
    0x98, 
    0xc8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x28 = { image_data_Font_0x28,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x29[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // ∙∙███
    // █∙∙██
    // ██∙██
    // ██∙∙█
    // ██∙∙█
    // ███∙█
    // ███∙█
    // ██∙∙█
    // ██∙∙█
    // ██∙∙█
    // ██∙██
    // ∙∙∙██
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0x38, 
    0x98, 
    0xd8, 
    0xc8, 
    0xc8, 
    0xe8, 
    0xe8, 
    0xc8, 
    0xc8, 
    0xc8, 
    0xd8, 
    0x18, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x29 = { image_data_Font_0x29,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2a[21] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ███∙██
    // █∙█∙∙█
    // ██∙∙██
    // █∙∙∙∙█
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xec, 
    0xa4, 
    0xcc, 
    0x84, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x2a = { image_data_Font_0x2a,
    6, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2b[21] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██∙███
    // ██∙███
    // █∙∙∙∙█
    // ██∙███
    // ██∙███
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xdc, 
    0xdc, 
    0x84, 
    0xdc, 
    0xdc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x2b = { image_data_Font_0x2b,
    6, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2c[21] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ██∙█
    // █∙∙█
    // █∙██
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xd0, 
    0x90, 
    0xb0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x2c = { image_data_Font_0x2c,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2d[21] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // █∙∙∙∙█
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0x84, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x2d = { image_data_Font_0x2d,
    6, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2e[21] = {
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x2e = { image_data_Font_0x2e,
    3, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2f[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ████∙∙█
    // ████∙██
    // ████∙██
    // ███∙∙██
    // ███∙███
    // ██∙∙███
    // ██∙████
    // ██∙████
    // █∙∙████
    // █∙█████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xf2, 
    0xf6, 
    0xf6, 
    0xe6, 
    0xee, 
    0xce, 
    0xde, 
    0xde, 
    0x9e, 
    0xbe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x2f = { image_data_Font_0x2f,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x30[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ███∙∙∙∙██
    // ██∙███∙∙█
    // █∙∙████∙█
    // █∙█████∙∙
    // █∙█████∙∙
    // █∙█████∙∙
    // █∙█████∙∙
    // █∙∙████∙█
    // ██∙███∙∙█
    // ███∙∙∙∙██
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xe1, 0x80, 
    0xdc, 0x80, 
    0x9e, 0x80, 
    0xbe, 0x00, 
    0xbe, 0x00, 
    0xbe, 0x00, 
    0xbe, 0x00, 
    0x9e, 0x80, 
    0xdc, 0x80, 
    0xe1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x30 = { image_data_Font_0x30,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x31[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // ██∙∙█
    // █∙∙∙█
    // █∙█∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xc8, 
    0x88, 
    0xa8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x31 = { image_data_Font_0x31,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x32[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙██
    // █∙███∙∙█
    // ██████∙█
    // ██████∙█
    // █████∙∙█
    // ████∙∙██
    // ███∙∙███
    // ██∙∙████
    // █∙∙█████
    // █∙∙∙∙∙∙∙
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc3, 
    0xb9, 
    0xfd, 
    0xfd, 
    0xf9, 
    0xf3, 
    0xe7, 
    0xcf, 
    0x9f, 
    0x80, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x32 = { image_data_Font_0x32,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x33[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙██
    // █∙███∙∙█
    // ██████∙█
    // █████∙∙█
    // ██∙∙∙∙██
    // █████∙∙█
    // ██████∙█
    // ██████∙█
    // █∙███∙∙█
    // █∙∙∙∙∙██
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x83, 
    0xb9, 
    0xfd, 
    0xf9, 
    0xc3, 
    0xf9, 
    0xfd, 
    0xfd, 
    0xb9, 
    0x83, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x33 = { image_data_Font_0x33,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x34[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █████∙∙█
    // ████∙∙∙█
    // ███∙∙∙∙█
    // ██∙∙█∙∙█
    // ██∙██∙∙█
    // █∙███∙∙█
    // ∙∙∙∙∙∙∙∙
    // █████∙∙█
    // █████∙∙█
    // █████∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xf9, 
    0xf1, 
    0xe1, 
    0xc9, 
    0xd9, 
    0xb9, 
    0x00, 
    0xf9, 
    0xf9, 
    0xf9, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x34 = { image_data_Font_0x34,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x35[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // █∙██████
    // █∙██████
    // █∙∙∙∙∙██
    // █∙███∙∙█
    // ██████∙█
    // ██████∙█
    // ██████∙█
    // █∙███∙∙█
    // █∙∙∙∙∙██
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xbf, 
    0xbf, 
    0x83, 
    0xb9, 
    0xfd, 
    0xfd, 
    0xfd, 
    0xb9, 
    0x83, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x35 = { image_data_Font_0x35,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x36[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ███∙∙∙∙██
    // ██∙∙█████
    // █∙∙██████
    // █∙█∙∙∙███
    // █∙∙███∙██
    // █∙████∙∙█
    // █∙████∙∙█
    // █∙████∙∙█
    // █∙∙███∙██
    // ██∙∙∙∙███
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xe1, 0x80, 
    0xcf, 0x80, 
    0x9f, 0x80, 
    0xa3, 0x80, 
    0x9d, 0x80, 
    0xbc, 0x80, 
    0xbc, 0x80, 
    0xbc, 0x80, 
    0x9d, 0x80, 
    0xc3, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x36 = { image_data_Font_0x36,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x37[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙█
    // ██████∙█
    // █████∙██
    // █████∙██
    // ████∙∙██
    // ████∙███
    // ███∙∙███
    // ███∙████
    // ██∙∙████
    // ██∙█████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x01, 
    0xfd, 
    0xfb, 
    0xfb, 
    0xf3, 
    0xf7, 
    0xe7, 
    0xef, 
    0xcf, 
    0xdf, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x37 = { image_data_Font_0x37,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x38[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙██
    // █∙∙███∙█
    // █∙████∙█
    // █∙∙███∙█
    // ██∙∙∙∙██
    // █∙∙███∙█
    // █∙████∙∙
    // █∙████∙∙
    // █∙∙███∙█
    // ██∙∙∙∙██
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc3, 
    0x9d, 
    0xbd, 
    0x9d, 
    0xc3, 
    0x9d, 
    0xbc, 
    0xbc, 
    0x9d, 
    0xc3, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x38 = { image_data_Font_0x38,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x39[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙███
    // █∙∙███∙██
    // █∙████∙∙█
    // █∙████∙∙█
    // █∙∙███∙∙█
    // ██∙∙∙∙∙∙█
    // ██████∙∙█
    // ██████∙██
    // █████∙∙██
    // ██∙∙∙████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc3, 0x80, 
    0x9d, 0x80, 
    0xbc, 0x80, 
    0xbc, 0x80, 
    0x9c, 0x80, 
    0xc0, 0x80, 
    0xfc, 0x80, 
    0xfd, 0x80, 
    0xf9, 0x80, 
    0xc7, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x39 = { image_data_Font_0x39,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3a[21] = {
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x3a = { image_data_Font_0x3a,
    3, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3b[21] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ██∙█
    // ████
    // ████
    // ████
    // ████
    // ████
    // ██∙█
    // █∙∙█
    // █∙██
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xd0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xd0, 
    0x90, 
    0xb0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x3b = { image_data_Font_0x3b,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3c[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██████∙█
    // ████∙∙██
    // ██∙∙████
    // █∙██████
    // ██∙∙∙███
    // ████∙∙∙█
    // ██████∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xfd, 
    0xf3, 
    0xcf, 
    0xbf, 
    0xc7, 
    0xf1, 
    0xfd, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x3c = { image_data_Font_0x3c,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3d[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙∙∙
    // ███████
    // ███████
    // █∙∙∙∙∙∙
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x80, 
    0xfe, 
    0xfe, 
    0x80, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x3d = { image_data_Font_0x3d,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3e[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙██████
    // █∙∙∙████
    // ███∙∙∙██
    // █████∙∙█
    // ███∙∙∙██
    // █∙∙∙████
    // █∙██████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbf, 
    0x8f, 
    0xe3, 
    0xf9, 
    0xe3, 
    0x8f, 
    0xbf, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x3e = { image_data_Font_0x3e,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3f[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙██
    // █∙███∙█
    // █████∙∙
    // █████∙█
    // ████∙∙█
    // ███∙███
    // ██∙∙███
    // ███████
    // ███████
    // ██∙∙███
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x86, 
    0xba, 
    0xf8, 
    0xfa, 
    0xf2, 
    0xee, 
    0xce, 
    0xfe, 
    0xfe, 
    0xce, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x3f = { image_data_Font_0x3f,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x40[42] = {
    // █████████████
    // █████████████
    // █████████████
    // █████████████
    // █████████████
    // ████∙∙∙∙∙∙███
    // ██∙∙∙████∙∙██
    // ██∙███████∙∙█
    // █∙███∙∙∙∙██∙█
    // █∙██∙∙██∙██∙█
    // █∙██∙███∙██∙█
    // █∙██∙██∙∙█∙∙█
    // █∙██∙∙∙∙∙∙∙██
    // █∙∙██████████
    // ██∙∙█████████
    // ███∙∙∙∙∙∙████
    // █████████████
    // █████████████
    // █████████████
    // █████████████
    // █████████████
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xf0, 0x38, 
    0xc7, 0x98, 
    0xdf, 0xc8, 
    0xb8, 0x68, 
    0xb3, 0x68, 
    0xb7, 0x68, 
    0xb6, 0x48, 
    0xb0, 0x18, 
    0x9f, 0xf8, 
    0xcf, 0xf8, 
    0xe0, 0x78, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8
};
static const tImage Font_0x40 = { image_data_Font_0x40,
    13, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x41[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ████∙∙████
    // ████∙∙████
    // ████∙█∙███
    // ███∙██∙███
    // ███∙██∙∙██
    // ██∙∙███∙██
    // ██∙∙∙∙∙∙██
    // ██∙████∙∙█
    // █∙∙█████∙█
    // █∙██████∙∙
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf5, 0xc0, 
    0xed, 0xc0, 
    0xec, 0xc0, 
    0xce, 0xc0, 
    0xc0, 0xc0, 
    0xde, 0x40, 
    0x9f, 0x40, 
    0xbf, 0x00, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x41 = { image_data_Font_0x41,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x42[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙∙∙∙∙██
    // █∙████∙∙█
    // █∙█████∙█
    // █∙████∙∙█
    // █∙∙∙∙∙∙██
    // █∙████∙∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙∙∙∙∙∙██
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x81, 0x80, 
    0xbc, 0x80, 
    0xbe, 0x80, 
    0xbc, 0x80, 
    0x81, 0x80, 
    0xbc, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0x81, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x42 = { image_data_Font_0x42,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x43[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙∙██
    // ██∙∙████∙█
    // █∙∙███████
    // █∙████████
    // █∙████████
    // █∙████████
    // █∙████████
    // █∙∙███████
    // ██∙∙████∙█
    // ███∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe0, 0xc0, 
    0xcf, 0x40, 
    0x9f, 0xc0, 
    0xbf, 0xc0, 
    0xbf, 0xc0, 
    0xbf, 0xc0, 
    0xbf, 0xc0, 
    0x9f, 0xc0, 
    0xcf, 0x40, 
    0xe0, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x43 = { image_data_Font_0x43,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x44[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙███
    // █∙████∙∙██
    // █∙█████∙∙█
    // █∙██████∙█
    // █∙██████∙█
    // █∙██████∙█
    // █∙██████∙█
    // █∙█████∙∙█
    // █∙████∙∙██
    // █∙∙∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x81, 0xc0, 
    0xbc, 0xc0, 
    0xbe, 0x40, 
    0xbf, 0x40, 
    0xbf, 0x40, 
    0xbf, 0x40, 
    0xbf, 0x40, 
    0xbe, 0x40, 
    0xbc, 0xc0, 
    0x81, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x44 = { image_data_Font_0x44,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x45[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙∙∙∙∙██
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xbf, 
    0xbf, 
    0xbf, 
    0x83, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0x81, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x45 = { image_data_Font_0x45,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x46[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙∙∙∙∙██
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xbf, 
    0xbf, 
    0xbf, 
    0x83, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x46 = { image_data_Font_0x46,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x47[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙∙∙██
    // ██∙∙████∙█
    // █∙∙███████
    // █∙████████
    // █∙████∙∙∙█
    // █∙██████∙█
    // █∙██████∙█
    // █∙∙█████∙█
    // ██∙∙████∙█
    // ███∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe0, 0xc0, 
    0xcf, 0x40, 
    0x9f, 0xc0, 
    0xbf, 0xc0, 
    0xbc, 0x40, 
    0xbf, 0x40, 
    0xbf, 0x40, 
    0x9f, 0x40, 
    0xcf, 0x40, 
    0xe0, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x47 = { image_data_Font_0x47,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x48[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙∙∙∙∙∙∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0x80, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x48 = { image_data_Font_0x48,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x49[21] = {
    // ███
    // ███
    // ███
    // ███
    // ███
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x49 = { image_data_Font_0x49,
    3, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4a[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ██∙∙█
    // ∙∙∙██
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xc8, 
    0x18, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x4a = { image_data_Font_0x4a,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4b[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙████∙∙∙
    // █∙████∙██
    // █∙███∙███
    // █∙██∙████
    // █∙∙∙∙████
    // █∙█∙∙████
    // █∙██∙∙███
    // █∙███∙∙██
    // █∙████∙██
    // █∙█████∙∙
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xbc, 0x00, 
    0xbd, 0x80, 
    0xbb, 0x80, 
    0xb7, 0x80, 
    0x87, 0x80, 
    0xa7, 0x80, 
    0xb3, 0x80, 
    0xb9, 0x80, 
    0xbd, 0x80, 
    0xbe, 0x00, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x4b = { image_data_Font_0x4b,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4c[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0x81, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x4c = { image_data_Font_0x4c,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4d[42] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █∙∙██████∙∙█
    // █∙∙██████∙∙█
    // █∙∙█████∙∙∙█
    // █∙█∙████∙∙∙█
    // █∙█∙███∙∙∙∙█
    // █∙█∙∙██∙█∙∙█
    // █∙██∙█∙∙█∙∙█
    // █∙██∙∙∙██∙∙█
    // █∙███∙∙██∙∙█
    // █∙███∙███∙∙█
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0x9f, 0x90, 
    0x9f, 0x90, 
    0x9f, 0x10, 
    0xaf, 0x10, 
    0xae, 0x10, 
    0xa6, 0x90, 
    0xb4, 0x90, 
    0xb1, 0x90, 
    0xb9, 0x90, 
    0xbb, 0x90, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x4d = { image_data_Font_0x4d,
    12, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4e[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙████∙∙█
    // █∙∙████∙∙█
    // █∙∙∙███∙∙█
    // █∙█∙∙██∙∙█
    // █∙██∙██∙∙█
    // █∙██∙∙█∙∙█
    // █∙███∙∙∙∙█
    // █∙████∙∙∙█
    // █∙████∙∙∙█
    // █∙█████∙∙█
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x9e, 0x40, 
    0x9e, 0x40, 
    0x8e, 0x40, 
    0xa6, 0x40, 
    0xb6, 0x40, 
    0xb2, 0x40, 
    0xb8, 0x40, 
    0xbc, 0x40, 
    0xbc, 0x40, 
    0xbe, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x4e = { image_data_Font_0x4e,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4f[42] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ███∙∙∙∙∙████
    // ██∙∙████∙∙██
    // █∙∙██████∙██
    // █∙███████∙∙█
    // █∙███████∙∙█
    // █∙███████∙∙█
    // █∙███████∙∙█
    // █∙∙██████∙██
    // ██∙∙███∙∙∙██
    // ███∙∙∙∙∙████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xe0, 0xf0, 
    0xcf, 0x30, 
    0x9f, 0xb0, 
    0xbf, 0x90, 
    0xbf, 0x90, 
    0xbf, 0x90, 
    0xbf, 0x90, 
    0x9f, 0xb0, 
    0xce, 0x30, 
    0xe0, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x4f = { image_data_Font_0x4f,
    12, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x50[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // █∙████∙∙
    // █∙█████∙
    // █∙█████∙
    // █∙████∙∙
    // █∙∙∙∙∙∙█
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙██████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xbc, 
    0xbe, 
    0xbe, 
    0xbc, 
    0x81, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x50 = { image_data_Font_0x50,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x51[42] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙∙∙███
    // ██∙∙███∙∙∙█
    // █∙∙██████∙█
    // █∙███████∙∙
    // █∙███████∙∙
    // █∙███████∙∙
    // █∙███████∙∙
    // █∙∙██████∙█
    // ██∙∙████∙██
    // ███∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe0, 0xe0, 
    0xce, 0x20, 
    0x9f, 0xa0, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0x9f, 0xa0, 
    0xcf, 0x60, 
    0xe0, 0x00, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x51 = { image_data_Font_0x51,
    11, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x52[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙∙∙∙∙██
    // █∙████∙∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙████∙∙█
    // █∙∙∙∙∙∙██
    // █∙███∙███
    // █∙███∙∙██
    // █∙████∙██
    // █∙████∙∙█
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x81, 0x80, 
    0xbc, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0xbc, 0x80, 
    0x81, 0x80, 
    0xbb, 0x80, 
    0xb9, 0x80, 
    0xbd, 0x80, 
    0xbc, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x52 = { image_data_Font_0x52,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x53[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙∙█
    // █∙∙███∙█
    // █∙██████
    // █∙∙█████
    // ██∙∙∙███
    // ███∙∙∙██
    // █████∙∙█
    // ██████∙█
    // █∙███∙∙█
    // █∙∙∙∙∙██
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc1, 
    0x9d, 
    0xbf, 
    0x9f, 
    0xc7, 
    0xe3, 
    0xf9, 
    0xfd, 
    0xb9, 
    0x83, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x53 = { image_data_Font_0x53,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x54[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x00, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xe7, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x54 = { image_data_Font_0x54,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x55[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙█████∙∙█
    // █∙∙███∙∙██
    // ███∙∙∙∙███
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0xbe, 0x40, 
    0x9c, 0xc0, 
    0xe1, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x55 = { image_data_Font_0x55,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x56[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙██████∙∙
    // █∙∙█████∙█
    // ██∙████∙∙█
    // ██∙████∙██
    // ██∙∙███∙██
    // ███∙██∙∙██
    // ███∙∙█∙███
    // ████∙∙∙███
    // ████∙∙████
    // ████∙∙████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xbf, 0x00, 
    0x9f, 0x40, 
    0xde, 0x40, 
    0xde, 0xc0, 
    0xce, 0xc0, 
    0xec, 0xc0, 
    0xe5, 0xc0, 
    0xf1, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x56 = { image_data_Font_0x56,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x57[42] = {
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // █∙████∙∙████∙█
    // █∙∙███∙∙███∙∙█
    // █∙∙███∙∙███∙∙█
    // ██∙██∙∙∙∙██∙██
    // ██∙██∙██∙██∙██
    // ██∙∙█∙██∙█∙∙██
    // ██∙∙█∙██∙█∙∙██
    // ███∙∙∙██∙∙∙███
    // ███∙∙████∙∙███
    // ███∙∙████∙∙███
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xbc, 0xf4, 
    0x9c, 0xe4, 
    0x9c, 0xe4, 
    0xd8, 0x6c, 
    0xdb, 0x6c, 
    0xcb, 0x4c, 
    0xcb, 0x4c, 
    0xe3, 0x1c, 
    0xe7, 0x9c, 
    0xe7, 0x9c, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc
};
static const tImage Font_0x57 = { image_data_Font_0x57,
    14, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x58[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙████∙∙█
    // ██∙████∙██
    // ███∙██∙∙██
    // ███∙∙∙∙███
    // ████∙∙████
    // ████∙∙████
    // ███∙∙∙∙███
    // ██∙∙██∙∙██
    // ██∙████∙∙█
    // █∙∙█████∙∙
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x9e, 0x40, 
    0xde, 0xc0, 
    0xec, 0xc0, 
    0xe1, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xe1, 0xc0, 
    0xcc, 0xc0, 
    0xde, 0x40, 
    0x9f, 0x00, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x58 = { image_data_Font_0x58,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x59[42] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙█████∙∙█
    // █∙∙████∙██
    // ██∙∙██∙∙██
    // ███∙██∙███
    // ███∙∙∙∙███
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ████∙∙████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xbe, 0x40, 
    0x9e, 0xc0, 
    0xcc, 0xc0, 
    0xed, 0xc0, 
    0xe1, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xf3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x59 = { image_data_Font_0x59,
    10, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5a[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙∙∙∙∙∙█
    // ██████∙██
    // █████∙∙██
    // ████∙∙███
    // ████∙████
    // ███∙∙████
    // ██∙∙█████
    // ██∙██████
    // █∙∙██████
    // █∙∙∙∙∙∙∙█
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x80, 0x80, 
    0xfd, 0x80, 
    0xf9, 0x80, 
    0xf3, 0x80, 
    0xf7, 0x80, 
    0xe7, 0x80, 
    0xcf, 0x80, 
    0xdf, 0x80, 
    0x9f, 0x80, 
    0x80, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x5a = { image_data_Font_0x5a,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5b[21] = {
    // ████
    // ████
    // ████
    // ████
    // █∙∙∙
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙∙∙
    // ████
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0x80, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0x80, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x5b = { image_data_Font_0x5b,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5c[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙█████
    // █∙∙████
    // ██∙████
    // ██∙████
    // ██∙∙███
    // ███∙███
    // ███∙∙██
    // ████∙██
    // ████∙██
    // ████∙∙█
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xbe, 
    0x9e, 
    0xde, 
    0xde, 
    0xce, 
    0xee, 
    0xe6, 
    0xf6, 
    0xf6, 
    0xf2, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x5c = { image_data_Font_0x5c,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5d[21] = {
    // ████
    // ████
    // ████
    // ████
    // ∙∙∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ██∙∙
    // ∙∙∙∙
    // ████
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0x00, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0x00, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x5d = { image_data_Font_0x5d,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5e[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ███∙████
    // ███∙∙███
    // ██∙█∙∙██
    // ██∙██∙██
    // █∙███∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xef, 
    0xe7, 
    0xd3, 
    0xdb, 
    0xb9, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x5e = { image_data_Font_0x5e,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5f[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙∙█
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x82, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x5f = { image_data_Font_0x5f,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x60[21] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // █∙██
    // ██∙█
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xb0, 
    0xd0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x60 = { image_data_Font_0x60,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x61[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙██
    // █████∙∙█
    // ██∙∙∙█∙█
    // █∙███∙∙█
    // █∙████∙█
    // █∙███∙∙█
    // ██∙∙∙█∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x83, 
    0xf9, 
    0xc5, 
    0xb9, 
    0xbd, 
    0xb9, 
    0xc5, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x61 = { image_data_Font_0x61,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x62[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙███████
    // █∙███████
    // █∙███████
    // █∙█∙∙∙∙██
    // █∙∙███∙∙█
    // █∙█████∙█
    // █∙█████∙∙
    // █∙█████∙█
    // █∙∙███∙∙█
    // █∙█∙∙∙∙██
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0xa1, 0x80, 
    0x9c, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x00, 
    0xbe, 0x80, 
    0x9c, 0x80, 
    0xa1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x62 = { image_data_Font_0x62,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x63[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙∙█
    // █∙∙███∙█
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙∙███∙█
    // ██∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc1, 
    0x9d, 
    0xbf, 
    0xbf, 
    0xbf, 
    0x9d, 
    0xc1, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x63 = { image_data_Font_0x63,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x64[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ███████∙█
    // ███████∙█
    // ███████∙█
    // ██∙∙∙∙█∙█
    // █∙∙███∙∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙∙███∙∙█
    // ██∙∙∙∙█∙█
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xfe, 0x80, 
    0xfe, 0x80, 
    0xfe, 0x80, 
    0xc2, 0x80, 
    0x9c, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0x9c, 0x80, 
    0xc2, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x64 = { image_data_Font_0x64,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x65[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙███
    // █∙∙███∙██
    // █∙████∙∙█
    // █∙∙∙∙∙∙∙█
    // █∙███████
    // █∙∙████∙█
    // ██∙∙∙∙∙██
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc3, 0x80, 
    0x9d, 0x80, 
    0xbc, 0x80, 
    0x80, 0x80, 
    0xbf, 0x80, 
    0x9e, 0x80, 
    0xc1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x65 = { image_data_Font_0x65,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x66[21] = {
    // █████
    // █████
    // █████
    // █████
    // ██∙∙∙
    // ██∙██
    // █∙∙██
    // █∙∙██
    // ∙∙∙∙█
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xc0, 
    0xd8, 
    0x98, 
    0x98, 
    0x08, 
    0x98, 
    0x98, 
    0x98, 
    0x98, 
    0x98, 
    0x98, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x66 = { image_data_Font_0x66,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x67[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙█∙█
    // █∙∙███∙∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙∙███∙∙█
    // ██∙∙∙∙█∙█
    // ███████∙█
    // ██∙███∙∙█
    // ██∙∙∙∙∙██
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc2, 0x80, 
    0x9c, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0x9c, 0x80, 
    0xc2, 0x80, 
    0xfe, 0x80, 
    0xdc, 0x80, 
    0xc1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x67 = { image_data_Font_0x67,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x68[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙█∙∙∙∙█
    // █∙∙███∙█
    // █∙████∙∙
    // █∙████∙∙
    // █∙████∙∙
    // █∙████∙∙
    // █∙████∙∙
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xa1, 
    0x9d, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x68 = { image_data_Font_0x68,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x69[21] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // █∙∙█
    // ████
    // ████
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0x90, 
    0xf0, 
    0xf0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x69 = { image_data_Font_0x69,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6a[21] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // █∙∙█
    // ████
    // ████
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // ∙∙██
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0x90, 
    0xf0, 
    0xf0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0x30, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x6a = { image_data_Font_0x6a,
    4, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6b[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙███∙∙█
    // █∙██∙∙██
    // █∙█∙∙███
    // █∙∙∙████
    // █∙█∙∙███
    // █∙██∙∙██
    // █∙███∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbf, 
    0xbf, 
    0xbf, 
    0xb9, 
    0xb3, 
    0xa7, 
    0x8f, 
    0xa7, 
    0xb3, 
    0xb9, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x6b = { image_data_Font_0x6b,
    8, 21, 8};
#endif

#if (0x049 == 0x0)
static const uint8_t image_data_Font_0x6c[21] = {
    // ███
    // ███
    // ███
    // ███
    // ███
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x6c = { image_data_Font_0x6c,
    3, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6d[42] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █∙█∙∙∙█∙∙∙∙█
    // █∙∙██∙∙███∙█
    // █∙███∙∙███∙█
    // █∙███∙∙███∙█
    // █∙███∙∙███∙█
    // █∙███∙∙███∙█
    // █∙███∙∙███∙█
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xa2, 0x10, 
    0x99, 0xd0, 
    0xb9, 0xd0, 
    0xb9, 0xd0, 
    0xb9, 0xd0, 
    0xb9, 0xd0, 
    0xb9, 0xd0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x6d = { image_data_Font_0x6d,
    12, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6e[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙█∙∙∙∙█
    // █∙∙███∙█
    // █∙████∙∙
    // █∙████∙∙
    // █∙████∙∙
    // █∙████∙∙
    // █∙████∙∙
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xa1, 
    0x9d, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x6e = { image_data_Font_0x6e,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6f[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙∙██
    // █∙∙███∙∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙∙███∙∙█
    // ██∙∙∙∙∙██
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc1, 0x80, 
    0x9c, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0x9c, 0x80, 
    0xc1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x6f = { image_data_Font_0x6f,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x70[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙█∙∙∙∙██
    // █∙∙███∙∙█
    // █∙█████∙█
    // █∙█████∙∙
    // █∙█████∙█
    // █∙∙███∙∙█
    // █∙█∙∙∙∙██
    // █∙███████
    // █∙███████
    // █∙███████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xa1, 0x80, 
    0x9c, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x00, 
    0xbe, 0x80, 
    0x9c, 0x80, 
    0xa1, 0x80, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0xbf, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x70 = { image_data_Font_0x70,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x71[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // ██∙∙∙∙█∙█
    // █∙∙███∙∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙█████∙█
    // █∙∙███∙∙█
    // ██∙∙∙∙█∙█
    // ███████∙█
    // ███████∙█
    // ███████∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xc2, 0x80, 
    0x9c, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0xbe, 0x80, 
    0x9c, 0x80, 
    0xc2, 0x80, 
    0xfe, 0x80, 
    0xfe, 0x80, 
    0xfe, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x71 = { image_data_Font_0x71,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x72[21] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // █∙█∙∙█
    // █∙∙███
    // █∙████
    // █∙████
    // █∙████
    // █∙████
    // █∙████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xa4, 
    0x9c, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xbc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x72 = { image_data_Font_0x72,
    6, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x73[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙∙█
    // █∙███∙█
    // █∙█████
    // ██∙∙∙██
    // ████∙∙█
    // █∙███∙█
    // █∙∙∙∙██
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x82, 
    0xba, 
    0xbe, 
    0xc6, 
    0xf2, 
    0xba, 
    0x86, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x73 = { image_data_Font_0x73,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x74[21] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █∙∙██
    // █∙∙██
    // ∙∙∙∙█
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // █∙∙██
    // ██∙∙∙
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0x98, 
    0x98, 
    0x08, 
    0x98, 
    0x98, 
    0x98, 
    0x98, 
    0x98, 
    0xc0, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x74 = { image_data_Font_0x74,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x75[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙████∙█
    // █∙████∙█
    // █∙████∙█
    // █∙████∙█
    // █∙████∙█
    // █∙∙██∙∙█
    // ██∙∙∙█∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbd, 
    0xbd, 
    0xbd, 
    0xbd, 
    0xbd, 
    0x99, 
    0xc5, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x75 = { image_data_Font_0x75,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x76[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙████∙∙
    // █∙∙██∙∙█
    // ██∙██∙∙█
    // ██∙∙█∙██
    // ██∙∙∙∙██
    // ███∙∙███
    // ███∙∙███
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbc, 
    0x99, 
    0xd9, 
    0xcb, 
    0xc3, 
    0xe7, 
    0xe7, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x76 = { image_data_Font_0x76,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x77[42] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙███∙∙██∙∙
    // █∙∙██∙∙██∙█
    // █∙∙█∙∙∙██∙█
    // ██∙█∙█∙█∙∙█
    // ██∙█∙██∙∙██
    // ██∙∙∙██∙∙██
    // ███∙███∙∙██
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xb9, 0x80, 
    0x99, 0xa0, 
    0x91, 0xa0, 
    0xd5, 0x20, 
    0xd6, 0x60, 
    0xc6, 0x60, 
    0xee, 0x60, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage Font_0x77 = { image_data_Font_0x77,
    11, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x78[42] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙███∙∙█
    // ██∙∙█∙∙██
    // ███∙∙∙███
    // ███∙∙████
    // ███∙∙∙███
    // ██∙██∙∙██
    // █∙∙███∙∙█
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x9c, 0x80, 
    0xc9, 0x80, 
    0xe3, 0x80, 
    0xe7, 0x80, 
    0xe3, 0x80, 
    0xd9, 0x80, 
    0x9c, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x78 = { image_data_Font_0x78,
    9, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x79[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙████∙∙
    // █∙∙███∙█
    // ██∙██∙∙█
    // ██∙∙█∙∙█
    // ███∙█∙██
    // ███∙∙∙██
    // ███∙∙███
    // ███∙∙███
    // ███∙∙███
    // █∙∙∙████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xbc, 
    0x9d, 
    0xd9, 
    0xc9, 
    0xeb, 
    0xe3, 
    0xe7, 
    0xe7, 
    0xe7, 
    0x8f, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x79 = { image_data_Font_0x79,
    8, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7a[21] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙∙█
    // ████∙∙█
    // ███∙∙██
    // ███∙███
    // ██∙████
    // █∙∙████
    // █∙∙∙∙∙█
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x82, 
    0xf2, 
    0xe6, 
    0xee, 
    0xde, 
    0x9e, 
    0x82, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x7a = { image_data_Font_0x7a,
    7, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7b[21] = {
    // █████
    // █████
    // █████
    // █████
    // ██∙∙█
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ∙∙███
    // █∙∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙∙█
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xc8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0x38, 
    0x98, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xc8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x7b = { image_data_Font_0x7b,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7c[21] = {
    // ███
    // ███
    // ███
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x7c = { image_data_Font_0x7c,
    3, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7d[21] = {
    // █████
    // █████
    // █████
    // █████
    // █∙∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙∙█
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // █∙∙██
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0x98, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xc8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0x98, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x7d = { image_data_Font_0x7d,
    5, 21, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7e[21] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙██∙█
    // █∙██∙∙∙█
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x8d, 
    0xb1, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x7e = { image_data_Font_0x7e,
    8, 21, 8};
#endif


static const tChar Font_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font_0x21},
#else
  // character: '!' == ''
  {0x21, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font_0x22},
#else
  // character: '"' == ''
  {0x22, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font_0x23},
#else
  // character: '#' == ''
  {0x23, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font_0x24},
#else
  // character: '$' == ''
  {0x24, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font_0x26},
#else
  // character: '&' == ''
  {0x26, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font_0x27},
#else
  // character: ''' == ''
  {0x27, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font_0x28},
#else
  // character: '(' == ''
  {0x28, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font_0x29},
#else
  // character: ')' == ''
  {0x29, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font_0x60},
#else
  // character: '`' == ''
  {0x60, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font_0x},
#endif

#if (0x049 == 0x0)
  // character: 'l'
  {0x6c, &Font_0x6c},
#else
  // character: 'l' == 'I'
  {0x6c, &Font_0x49},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font_0x73},
#else
  // character: 's' == ''
  {0x73, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font_0x74},
#else
  // character: 't' == ''
  {0x74, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Font_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font_0x7e}
#else
  // character: '~' == ''
  {0x7e, &Font_0x}
#endif

};


const tFont Font = { 95, Font_array };

